version: "3"

volumes:
  subject_data:

services:
  subject-service:
    container_name: subject-service
    build: .
    image: cu-overflow/subject
    ports:
      - 8080:8080
    networks:
      - subject
    depends_on:
      subject-db:
        condition: service_healthy
  
  # subject db is for testing only
  subject-db:
    image: postgres:16.0-alpine3.18
    restart: always
    healthcheck:
      test: "pg_isready -d ${POSTGRES_DBNAME} -U ${POSTGRES_USER}"
      interval: 15s
      timeout: 5s
      retries: 5
    volumes:
      - subject_data:/var/lib/postgresql/data 
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    networks:
      - subject

networks:
  subject:
    name: subject_service
    driver: bridge
#    external: true