version: "3"

services:
  subject-service:
    container_name: subject_service
    build: .
    ports:
      - 8080:8080
    networks:
      - subject
  
  subject-db:
    image: postgres:16.0-alpine3.18
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - subject

networks:
  subject:
    driver: bridge
